# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Products' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
  
  # Pods for Products
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'ProductsTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'ProductsUITests' do
    # Pods for testing
  end
  
end
